### ISSUE TITLE
请求引用

### ISSUE THREAD

**Issue by drinktoomuchsax** [HuaYuXiao/OV5640-VGA#1]
学姐/学长好，请求在[SUSTech-EE-Course-Hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)里引用你的项目以及引用你的仓库内容：)

**Comment by HuaYuXiao** [comment]
谢谢，但我并不愿意共享这个项目，因为尚存有一些恶性bug没能成功解决。本项目由这个项目魔改而来👉https://github.com/YJ-Guan/Xilinx-NEXYS4_DDR-Drives-OV5640

**Comment by drinktoomuchsax** [comment]
好的，我明白了，respect
